### ISSUE TITLE
密码中含有小数点时会报错

### ISSUE THREAD

**Issue by Aerotic** [neucn/ipgw#28]
OS: Windows 
使用 cmd 时密码中含有小数点时会报错
`系统找不到指定的文件`
但是使用 powershell 则正常

**Comment by unbyte** [comment]
请使用`""`将密码包裹

**Comment by Aerotic** [comment]
> 请使用`""`将密码包裹

试了一下 确实这样好使

**Comment by Aerotic** [comment]
> 请使用`""`将密码包裹

顺便，好评闪电般的回复速度
