### ISSUE TITLE
win使用powershell安装，显示无法解析远程名字

### ISSUE THREAD

**Issue by lghosth** [neucn/ipgw#30]
以下是报错原文：
iwr : 未能解析此远程名称: 'raw.githubusercontent.com'
所在位置 行:1 字符: 1
+ iwr https://raw.githubusercontent.com/neucn/ipgw/master/install.ps1 - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebExce
    ption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by lghosth** [comment]
> 以下是报错原文：
> iwr : 未能解析此远程名称: 'raw.githubusercontent.com'
> 所在位置 行:1 字符: 1
> 
> * iwr https://raw.githubusercontent.com/neucn/ipgw/master/install.ps1 - ...
> * ```
>     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebExce
>     ption
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
>   ```

**Comment by unbyte** [comment]
应该解决了吧？看上去是网络原因

**Comment by lghosth** [comment]
> 应该解决了吧？看上去是网络原因
没错，网络原因。安装的时候没有注意到。
东西已经在用了，每次开机真的方便，tql
